### ISSUE TITLE
Could you please publish this repo in https://github.com/linkedin-faq, thanks

### ISSUE THREAD

**Issue by Ebazhanov** [wkm97/react-linkedin-quiz#1]
Hello, @wkm97!

I have sent you invitation to become member at https://github.com/linkedin-faq
the reason why I was inviting you is to ask publish your repo https://github.com/wkm97/react-linkedin-practices
to make it more visible for global network.

So I would be happy if you will do it, thank you in advance!

**Comment by wkm97** [comment]
Hi @Ebazhanov, thanks for the invitation but I couldn't find the invitation. This is the better version of it https://github.com/wkm97/md2practice, I could publish this instead.

**Comment by wkm97** [comment]
Hi @Ebazhanov , thanks for the invitation. This is the better version of it https://github.com/wkm97/md2practice, I could publish this instead.

**Comment by Ebazhanov** [comment]
Cool, I did not know )) Yes would be great if you could add this new version, thank you in advance! Going to close this issue.
